version: '2'
services:
    inwentaryzacja-app:
        image: inwentaryzacja
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://inwentaryzacja-mysql:3306/inwentaryzacja?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8090:8090
    inwentaryzacja-mysql:
        extends:
            file: mysql.yml
            service: inwentaryzacja-mysql
